### PR TITLE
Boost thread header for txdb.

### PR DESCRIPTION
**Pull request by chrisandrewca**
Hello! Adding this boost header fixes the WSL windows build. Probably not the right place for it but a good conversation starter?

### CODE REVIEW

**Comment by domob1812** [comment]
Thanks!  I think the right place would be https://github.com/bitcoin/bitcoin, on which this is mostly based.  There are some Namecoin-specific changes to `txdb.cpp`, though, so if Bitcoin builds fine for you and Namecoin is the culprit, then the right place would be https://github.com/namecoin/namecoin-core.

**Comment by chrisandrewca** [comment]
Yeah no problem. Bitcoin is building and Namecoin is not. Is it the right place in the file /style / etc. Should it be in another header? I think Namecoin is super cool. Thanks for the project.

**Comment by domob1812** [comment]
Ok, then yes, namecoin/namecoin-core is the place to put it.  If you create an issue there, please also specify what the error is with which it otherwise fails to build.  I'd like to better understand why exactly we need this, and if there's perhaps another, "more proper" fix for it.

**Comment by chrisandrewca** [comment]
Oh man will do. Thought was Namecoin proper. Cheers.

**Comment by domob1812** [comment]
Well, this was the original repository I started when I reimplemented Namecoin back in 2014, but the "official" repository is the other one in the Namecoin organisation.  Thanks!

**Pull request closed without merging**
